import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

// By default, the app generated by ng init will include the FormsModule, here we’re requiring the ReactiveFormsModule as well
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
// import { RouterModule, Routes } from '@angular/router';
import { AppRoutingModule } from './app-routing.module';


import { AppComponent } from './app.component';
import { HeaderComponent } from './header/header.component';
import { WordListComponent } from './word-list/word-list.component';
import { ContentFilterPipe } from './content-filter.pipe';
import { NewDefinitionComponent } from './new-definition/new-definition.component';
import { PracticeComponent } from './practice/practice.component';
import { EditDefinitionComponent } from './edit-definition/edit-definition.component';
import { DeleteDefinitionComponent } from './delete-definition/delete-definition.component';




@NgModule({
  declarations: [
    AppComponent,
    HeaderComponent,
    WordListComponent,
    ContentFilterPipe,
    NewDefinitionComponent,
    PracticeComponent,
    EditDefinitionComponent,
    DeleteDefinitionComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    AppRoutingModule,
    ReactiveFormsModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
